name: firestore_infrastructure_example
description: Example usage of dartzen_infrastructure_firestore
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.12
  dartzen_core:
    path: ../../dartzen_core
  dartzen_identity_domain:
    path: ../../dartzen_identity_domain
  dartzen_infrastructure_firestore:
    path: ../
