name: dartzen_demo_contracts
description: Shared contracts for ZenDemo client-server communication
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  dartzen_core:
    path: ../../../packages/dartzen_core

resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
