name: dartzen_demo_server
description: ZenDemo server application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  dartzen_core:
    path: ../../../packages/dartzen_core
  dartzen_demo_contracts:
    path: ../dartzen_demo_contracts
  dartzen_firestore:
    path: ../../../packages/dartzen_firestore
  dartzen_identity:
    path: ../../../packages/dartzen_identity
  dartzen_localization:
    path: ../../../packages/dartzen_localization
  dartzen_storage:
    path: ../../../packages/dartzen_storage
  dartzen_transport:
    path: ../../../packages/dartzen_transport
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1

resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
