name: dartzen_server_transport
description: Minimal Shelf middleware for DartZen transport layer
version: 0.1.0
homepage: https://dartzen.dev
repository: https://github.com/DartZenDev/DartZen
issue_tracker: https://github.com/DartZenDev/DartZen/issues
publish_to: none

environment:
  sdk: '>=3.10.3 <4.0.0'

resolution: workspace

dependencies:
  dartzen_transport:
    path: ../dartzen_transport
  shelf: ^1.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
