name: dartzen_ui_identity_example
description: Example app for dartzen_ui_identity.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.10.2 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^14.0.0

  dartzen_core:
    path: ../../dartzen_core
  dartzen_identity:
    path: ../../dartzen_identity
  dartzen_localization:
    path: ../../dartzen_localization
  dartzen_ui_navigation:
    path: ../../dartzen_ui_navigation
  dartzen_ui_identity:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
