name: dartzen_core
description: The core layer for the DartZen ecosystem. Provides universal result types, value objects, and shared contracts.
version: 0.0.1
homepage: https://dartzen.dev
repository: https://github.com/DartZenDev/DartZen
issue_tracker: https://github.com/DartZenDev/DartZen/issues

publish_to: none

environment:
  sdk: '>=3.10.3 <4.0.0'

resolution: workspace

topics:
  - architecture
  - functional
  - result

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
