name: dartzen_core
description: Core runtime for DartZen.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dartzen_shared:
    path: ../dartzen_shared
  shelf: ^1.4.2
  get_it: ^9.2.0
  logger: ^2.6.2
  firebase_admin: ^0.3.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
