name: dartzen_infrastructure_identity_example
description: Usage example for dartzen_infrastructure_identity.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  dartzen_core:
    path: ../../dartzen_core
  dartzen_identity_domain:
    path: ../../dartzen_identity_domain
  dartzen_infrastructure_identity:
    path: ..
