name: dartzen_infrastructure_identity_example
description: Example demonstrating dartzen_infrastructure_identity usage.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  dartzen_core:
    path: ../../dartzen_core
  dartzen_identity_contract:
    path: ../../dartzen_identity_contract
  dartzen_identity_domain:
    path: ../../dartzen_identity_domain
  dartzen_infrastructure_identity:
    path: ../
  dartzen_localization:
    path: ../../dartzen_localization
