name: dartzen_shared
description: Shared models and contracts for DartZen.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
