name: zen_demo_client
description: ZenDemo Flutter client application
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  dartzen_core:
    path: ../../../packages/dartzen_core
  dartzen_identity:
    path: ../../../packages/dartzen_identity
  dartzen_localization:
    path: ../../../packages/dartzen_localization
  dartzen_transport:
    path: ../../../packages/dartzen_transport
  dartzen_ui_identity:
    path: ../../../packages/dartzen_ui_identity
  dartzen_ui_navigation:
    path: ../../../packages/dartzen_ui_navigation
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  zen_demo_contracts:
    path: ../contracts

resolution: workspace

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/src/l10n/
